demo/config/routes.rb
Rails.application.routes.draw do
  resources :reasons
  resources :points
  resources :reasons do
    resources :points
  end
  get 'pages/index'
  root to: "pages#index"
end

demo/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

demo/app/models/cheer.rb
class Cheer < ApplicationRecord
end

demo/app/models/point.rb
class Point < ApplicationRecord
  belongs_to :reason
end

demo/app/models/reason.rb
class Reason < ApplicationRecord
  has_many :points

  scope :with_points, ->(include) { includes(:points) if include.present? && include.to_bool }
  
end

demo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

demo/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

demo/app/controllers/points_controller.rb
class PointsController < ApplicationController
  before_action :set_point, only: [:show, :edit, :update, :destroy]

  # GET /points
  # GET /points.json
  def index
    @points = Point.all
  end

  # GET /points/1
  # GET /points/1.json
  def show
  end

  # GET /points/new
  def new
    @point = Point.new
  end

  # GET /points/1/edit
  def edit
  end

  # POST /points
  # POST /points.json
  def create
    @point = Point.new(point_params)

    respond_to do |format|
      if @point.save
        format.html { redirect_to @point, notice: 'Point was successfully created.' }
        format.json { render :show, status: :created, location: @point }
      else
        format.html { render :new }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /points/1
  # PATCH/PUT /points/1.json
  def update
    respond_to do |format|
      if @point.update(point_params)
        format.html { redirect_to @point, notice: 'Point was successfully updated.' }
        format.json { render :show, status: :ok, location: @point }
      else
        format.html { render :edit }
        format.json { render json: @point.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /points/1
  # DELETE /points/1.json
  def destroy
    @point.destroy
    respond_to do |format|
      format.html { redirect_to points_url, notice: 'Point was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point
      @point = Point.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def point_params
      params.require(:point).permit(:text, :reason_id)
    end
end

demo/app/controllers/reasons_controller.rb
class ReasonsController < ApplicationController
  before_action :set_reason, only: [:show, :edit, :update, :destroy]

  # GET /reasons
  # GET /reasons.json
  def index
    @reasons = Reason.with_points(true).all
  end

  # GET /reasons/1
  # GET /reasons/1.json
  def show
  end

  # GET /reasons/new
  def new
    @reason = Reason.new
  end

  # GET /reasons/1/edit
  def edit
  end

  # POST /reasons
  # POST /reasons.json
  def create
    @reason = Reason.new(reason_params)

    respond_to do |format|
      if @reason.save
        format.html { redirect_to @reason, notice: 'Reason was successfully created.' }
        format.json { render :show, status: :created, location: @reason }
      else
        format.html { render :new }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reasons/1
  # PATCH/PUT /reasons/1.json
  def update
    respond_to do |format|
      if @reason.update(reason_params)
        format.html { redirect_to @reason, notice: 'Reason was successfully updated.' }
        format.json { render :show, status: :ok, location: @reason }
      else
        format.html { render :edit }
        format.json { render json: @reason.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reasons/1
  # DELETE /reasons/1.json
  def destroy
    @reason.destroy
    respond_to do |format|
      format.html { redirect_to reasons_url, notice: 'Reason was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reason
      @reason = Reason.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reason_params
      params.require(:reason).permit(:text)
    end
end

demo/app/helpers/application_helper.rb
module ApplicationHelper
end

demo/app/helpers/pages_helper.rb
module PagesHelper
end

demo/app/helpers/points_helper.rb
module PointsHelper
end

demo/app/helpers/reasons_helper.rb
module ReasonsHelper
end

demo/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="/">CoLabs</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/reasons">Reasons</a>
      </li>
    </ul>
  </div>
</nav>

demo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'hello_vue', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'hello_vue', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render '/layouts/navbar' %>
    <div id="app" class="container mt-4">
      <%= yield %>
    </div>
  </body>
</html>

demo/app/views/pages/index.html.erb
<hello-rails></hello-rails>

<hello-rails></hello-rails>

<hello-rails></hello-rails>

<hello-rails></hello-rails>

demo/app/views/points/_form.html.erb
<% if point.errors.any? %>
  <% point.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
  <% end %>
<% end %>
<%= form_with(model: point, local: true) do |form| -%>
<div class="card shadow-sm">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="form-group">
        <%= form.label :text, class: "font-weight-bold" %>
        <%= form.text_field :text, placeholder: "Enter text", class: "form-control" %>
      </div>
    </li>
    <li class="list-group-item">
      <div class="form-group">
        <%= form.label :reason_id, class: "font-weight-bold" %>
        <%= form.text_field :reason_id, placeholder: "Enter reason_id", class: "form-control" %>
      </div>
    </li>
  </ul>
  <div class="card-footer">
    <%= link_to "Cancel", point, class: 'btn btn-outline-secondary float-left' if point.persisted? %>
    <%= link_to "Cancel", points_path, class: 'btn btn-outline-secondary float-left' if !point.persisted? %>
    <%= form.submit "Save", class: "btn btn-primary float-right" if point.persisted? %>
    <%= form.submit "Create", class: "btn btn-primary float-right" if !point.persisted? %>
  </div>
</div>
<% end %>

demo/app/views/points/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Points", points_path %></li>
  <li class="breadcrumb-item"><%= link_to @point.id, @point %></li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<%= render 'form', point: @point %>

demo/app/views/points/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item active mr-auto">Points</li>
</ol>
<div class="card-columns">
  <% @points.each do |point| %>
    <div class="card card mb-4 shadow-sm">
      <div class="card-body">
        <h5 class="card-title"><%= link_to point.to_s, point %></h5>
        <p class="card-text"><%= point.created_at %></p>
      </div>
    </div>
  <% end %>
</div>

demo/app/views/points/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Points", points_path %></li>
  <li class="breadcrumb-item active">Add</li>
</ol>

<%= render 'form', point: @point %>

demo/app/views/points/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Points", points_path %></li>
  <li class="breadcrumb-item active mr-auto"><%= @point.id %></li> 
</ol>
<div class="card shadow-sm">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p class="font-weight-bold">Text</p>
      <p class="font-weight-normal"><%= @point.text %></p>
    </li>
    <li class="list-group-item">
      <p class="font-weight-bold">Reason</p>
      <p class="font-weight-normal"><%= @point.reason %></p>
    </li>
  </ul>
</div>

demo/app/views/reasons/_form.html.erb
<% if reason.errors.any? %>
  <% reason.errors.full_messages.each do |message| %>
  <div class="alert alert-danger" role="alert">
    <%= message %>
  </div>
  <% end %>
<% end %>
<%= form_with(model: reason, local: true) do |form| -%>
<div class="card shadow-sm">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <div class="form-group">
        <%= form.label :text, class: "font-weight-bold" %>
        <%= form.text_field :text, placeholder: "Enter text", class: "form-control" %>
      </div>
    </li>
  </ul>
  <div class="card-footer">
    <%= link_to "Cancel", reason, class: 'btn btn-outline-secondary float-left' if reason.persisted? %>
    <%= link_to "Cancel", reasons_path, class: 'btn btn-outline-secondary float-left' if !reason.persisted? %>
    <%= form.submit "Save", class: "btn btn-primary float-right" if reason.persisted? %>
    <%= form.submit "Create", class: "btn btn-primary float-right" if !reason.persisted? %>
  </div>
</div>
<% end %>

demo/app/views/reasons/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Reasons", reasons_path %></li>
  <li class="breadcrumb-item"><%= link_to @reason.id, @reason %></li>
  <li class="breadcrumb-item active">Edit</li>
</ol>

<%= render 'form', reason: @reason %>

demo/app/views/reasons/index.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item active mr-auto">Reasons</li>
</ol>
<div class="card-columns">
  <% @reasons.each do |reason| %>
    <div class="card card mb-4 shadow-sm">
      <div class="card-body">
        <h5 class="card-title"><%= link_to reason.text, reason %></h5>
      </div>
      <ul class="list-group list-group-flush">
        <% reason.points.each do |point| %>
          <li class="list-group-item"><%= point.text %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

demo/app/views/reasons/new.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Reasons", reasons_path %></li>
  <li class="breadcrumb-item active">Add</li>
</ol>

<%= render 'form', reason: @reason %>

demo/app/views/reasons/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link_to "Reasons", reasons_path %></li>
  <li class="breadcrumb-item active mr-auto"><%= @reason.id %></li> 
</ol>
<div class="card shadow-sm">
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <p class="font-weight-bold">Text</p>
      <p class="font-weight-normal"><%= @reason.text %></p>
    </li>
  </ul>
</div>